# Generated by Django 5.0.6 on 2026-05-21 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('tempo', models.PositiveIntegerField(default=120, verbose_name='Темп (BPM)')),
                ('key', models.CharField(choices=[('C', 'C'), ('C#', 'C#'), ('D', 'D'), ('D#', 'D#'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('G', 'G'), ('G#', 'G#'), ('A', 'A'), ('A#', 'A#'), ('B', 'B'), ('Cm', 'Cm'), ('C#m', 'C#m'), ('Dm', 'Dm'), ('D#m', 'D#m'), ('Em', 'Em'), ('Fm', 'Fm'), ('F#m', 'F#m'), ('Gm', 'Gm'), ('G#m', 'G#m'), ('Am', 'Am'), ('A#m', 'A#m'), ('Bm', 'Bm')], default='C', max_length=10, verbose_name='Тональність')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проєкт',
                'verbose_name_plural': 'Проєкти',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва доріжки')),
                ('file', models.FileField(upload_to='tracks/', verbose_name='Аудіофайл')),
                ('volume', models.FloatField(default=1.0, verbose_name='Гучність')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Аудіодоріжка',
                'verbose_name_plural': 'Аудіодоріжки',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
